"""Add"""

revision = 'e53a862585ac'
down_revision = 'f659949bf8b2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('status', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'status')
    # ### end Alembic commands ###
