"""add salary to job_posting"""

revision = 'f659949bf8b2'
down_revision = '20231104_0001'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('salary', sa.String(), nullable=True))
    op.add_column('job_postings', sa.Column('salary_predicted', sa.String(), nullable=True))
    op.add_column('job_postings', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'score')
    op.drop_column('job_postings', 'salary_predicted')
    op.drop_column('job_postings', 'salary')
    # ### end Alembic commands ###
